---
kind: pipeline
name: revive-docker

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: astamia/revive-adserver
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password