version: '3'
services:
  web:
    build: .
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - 8081:8080
